name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /var/www/xemaydienvinfastxanhmekong

            git pull origin main

            npm ci

            npm run build

            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/

            pm2 restart vinfastxanhmekong